name: Secret Workflow Demo

on: [push] # This workflow runs on every push to the repository, fulfilling Task 2's trigger

jobs:
  test_secret: # This is the job definition
    runs-on: ubuntu-latest # The runner environment

    steps:
      - name: Checkout repository # Step 1: Clone your repository's code
        uses: actions/checkout@v4

      - name: Use the secret # Step 2: Use the secret and validate its presence
        run: |
          # This line demonstrates using the secret and ensures it's masked in logs (Task 2 & 3)
          echo "The secret is ${{ secrets.SECRET }}"

          # This condition performs a 'task' using the secret (Task 2)
          # It verifies the secret is passed as an environment variable and is not empty.
          if [ -n "$SECRET" ]; then
            echo "Secret value is present" # Outcome for validation (Task 3)
          else
            echo "Secret value is missing"
            exit 1 # Fail the step if the secret is not found, ensuring proper execution check (Task 3)
          fi
        env:
          # This passes the GitHub Secret named 'SECRET' into an environment variable
          # also named 'SECRET' for use in the 'run' script.
          SECRET: ${{ secrets.SECRET }}
