name: GitHub Secret Workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        env:
          SECRET_VALUE: ${{ secrets.SECRET }}
        run: |
          The secret is \${{ secrets.SECRET }}"
